name: Build and Deploy .NET App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up the .NET Core SDK (adjust the version if needed)
    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'  # Change to '3.1' if your project is using .NET Core 3.1

    # Step 3: Restore the project dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Step 4: Build the project in Release configuration
    - name: Build the .NET app
      run: dotnet build --configuration Release

    # Step 5: Publish the app to a folder
    - name: Publish the .NET app
      run: dotnet publish -c Release -o ./publish

    # Step 6: List the files in the publish directory to verify output
    - name: List files in publish directory
      run: |
        ls -R ./publish

    # Step 7: Deploy to the FTP Server using the FTP Deploy Action
    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ftpupload.net                     # FTP server address
        username: ${{ secrets.FTP_USER }}         # FTP username (stored in GitHub secrets)
        password: ${{ secrets.FTP_PASS }}         # FTP password (stored in GitHub secrets)
        local-dir: '/Pages/'           # Path to static files (from .NET publish)
        server-dir: '/htdocs/'                    # Destination directory on FTP server
        protocol: 'ftps'                          # Protocol (use 'ftps' for secure FTP)
        log-level: 'verbose'                      # Set log level to 'verbose' for detailed output
