name: ASP.NET Core Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test, and Deploy ASP.NET Core Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.402'
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish the application
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ftpupload.net                # Your FTP server address
        username: ${{ secrets.FTP_USER }}    # FTP username (from GitHub Secrets)
        password: ${{ secrets.FTP_PASS }}    # FTP password (from GitHub Secrets)
        local-dir: './publish/'              # Local directory to upload (published app)
        server-dir: '/htdocs/'               # Destination directory on FTP server
        protocol: 'ftps'                     # Secure protocol for FTP transfer
        log-level: 'verbose'                 # Detailed logging
